### ISSUE TITLE
Building the project

### ISSUE THREAD

**Issue by BVijayKrishna** [mayankgupta022/OCR#1]
Hi Mayank,

Can you please give brief steps on how to build this application.

Thanks,
Vijay

**Comment by BVijayKrishna** [comment]
**I'm getting this error when calling         TessAPI api = TessAPI.INSTANCE;**


```
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: Unable to load library 'tesseract': dlopen(libtesseract.dylib, 1): Library not loaded: /opt/local/lib/liblept.4.dylib
  Referenced from: /Users/nisum/git/OCR/libtesseract.dylib
  Reason: image not found
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:127)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:170)
	at com.sun.jna.Library$Handler.<init>(Library.java:123)
	at com.sun.jna.Native.loadLibrary(Native.java:260)
	at com.sun.jna.Native.loadLibrary(Native.java:246)
	at net.sourceforge.tess4j.TessAPI.<clinit>(TessAPI.java:38)
```


Please help
